#!/bin/bash

# Base
alias clr='clear'
alias md="mkdir -p"
alias rd="rmdir"

# Eza (Better ls) Aliases
alias ls='eza --color=always --group-directories-first --icons=always'
alias ll='eza -lh --color=always --group-directories-first --icons=always'
alias la='eza -lah --color=always --group-directories-first --icons=always'
alias tree='eza --tree --color=always --icons=always'

alias mcp-inspector='npx @modelcontextprotocol/inspector'

# Editor
alias vi="nvim"
alias vim="nvim"

# podman, kubernetes
alias p="podman"
alias pc="podman-compose"
alias k="kubectl"

# Direct docker commands to Podman
alias docker="podman"

# Intercept 'docker compose' while passing all other 'docker' commands to podman
# docker() {
#   if [ "$1" = "compose" ]; then
#     shift
#     podman-compose "$@"
#   else
#     podman "$@"
#   fi
# }
